services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_URL: "sqlite:////app/data/reavaliacao.db"
    volumes:
      - dbdata:/app/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  dbdata:
